# Generated by Django 3.1.4 on 2020-12-12 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=140)),
                ('name', models.CharField(max_length=140)),
                ('done', models.BooleanField()),
            ],
            options={
                'ordering': ['Title'],
            },
        ),
    ]
